	modLoader="javafml"
	loaderVersion="[35,)"
	license="MIT"
	
[[mods]]
	modId="stackableverything"
	version="1.0"
	displayName="Everything is Stackable!"
	displayURL=""
	issueTrackerURL=""
	logoFile=""
	credits=""
	authors="Ed Ardolino"
	description='''
	Everything is Stackable!
'''

[[dependencies.stackableverything]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.stackableverything]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="AFTER"
    side="BOTH"
